# Generated by Django 3.1.1 on 2021-10-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bairros', models.CharField(max_length=10000)),
                ('Min', models.CharField(max_length=10000)),
                ('Max', models.CharField(max_length=10000)),
                ('Media', models.CharField(max_length=10000)),
                ('Moradores', models.CharField(max_length=10000)),
                ('HabitantesTotal', models.CharField(max_length=10000)),
                ('RendaMediapormorador', models.CharField(max_length=10000)),
                ('RendaMediaFamiliar', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPO', models.CharField(max_length=10000)),
                ('CLASSE', models.CharField(max_length=10000)),
                ('VALOR', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Razao', models.CharField(max_length=10000)),
                ('CNPJ', models.CharField(max_length=10000)),
                ('ATIVIDADE', models.CharField(max_length=10000)),
                ('PORTE', models.CharField(max_length=10000)),
                ('Endereco', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('previa', models.CharField(default='Some String', max_length=1000)),
                ('description', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('previa', models.CharField(default='Some String', max_length=1000)),
                ('description', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutoriaisPalestras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Tutoriais', 'Tutoriais'), ('Palestras', 'Palestras')], max_length=9)),
            ],
        ),
    ]
