# Generated by Django 3.1.1 on 2021-08-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieacif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagem/%Y/%m/%D/'),
        ),
    ]
