# Generated by Django 3.1.1 on 2021-08-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieacif', '0002_home_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bairros', models.CharField(max_length=255)),
                ('Mín', models.CharField(max_length=255)),
                ('Max', models.CharField(max_length=255)),
                ('Média', models.CharField(max_length=255)),
                ('Moradores', models.CharField(max_length=255)),
                ('Hab_Total', models.CharField(max_length=255)),
                ('Renda_Média_por_Morador', models.CharField(max_length=255)),
                ('Renda_Média_Familiar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=255)),
                ('Classe', models.CharField(max_length=255)),
                ('Valor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Razão_Social', models.CharField(max_length=255)),
                ('CNPJ', models.CharField(max_length=255)),
                ('Atividade_Econômica_CNAE', models.CharField(max_length=255)),
                ('Porte', models.CharField(max_length=255)),
                ('Endereço', models.CharField(max_length=255)),
            ],
        ),
    ]
