# Generated by Django 3.1.1 on 2021-08-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieacif', '0005_auto_20210831_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='Classe',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='Tipo',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='Valor',
            field=models.CharField(max_length=10000),
        ),
    ]
