# Generated by Django 3.1.1 on 2021-09-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieacif', '0007_auto_20210831_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
    ]
