# Generated by Django 3.1.1 on 2021-10-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieacif', '0010_tutoriaispalestras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumidores',
            old_name='Hab_Total',
            new_name='Habitantes_Total',
        ),
        migrations.RenameField(
            model_name='consumidores',
            old_name='Média',
            new_name='Media',
        ),
        migrations.RenameField(
            model_name='consumidores',
            old_name='Mín',
            new_name='Min',
        ),
        migrations.RenameField(
            model_name='consumidores',
            old_name='Renda_Média_Familiar',
            new_name='Renda_Media_Familiar',
        ),
        migrations.RenameField(
            model_name='consumidores',
            old_name='Renda_Média_por_Morador',
            new_name='Renda_Media_por_Morador',
        ),
    ]
