# Generated by Django 3.1.1 on 2021-10-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieacif', '0011_auto_20211005_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumidores',
            old_name='Habitantes_Total',
            new_name='HabitantesTotal',
        ),
    ]
