# Generated by Django 3.1.1 on 2021-10-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieacif', '0012_auto_20211005_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='Razão_Social',
            new_name='Atividade_Economica_CNAE',
        ),
        migrations.RenameField(
            model_name='empresas',
            old_name='Atividade_Econômica_CNAE',
            new_name='Razao_Social',
        ),
    ]
