# Generated by Django 3.1.1 on 2021-10-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieacif', '0014_auto_20211007_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumidores',
            old_name='RendaMediaPorMorador',
            new_name='RendaMediapormorador',
        ),
        migrations.RenameField(
            model_name='consumo',
            old_name='Classe',
            new_name='CLASSE',
        ),
        migrations.RenameField(
            model_name='consumo',
            old_name='Tipo',
            new_name='TIPO',
        ),
        migrations.RenameField(
            model_name='consumo',
            old_name='Valor',
            new_name='VALOR',
        ),
        migrations.RenameField(
            model_name='empresas',
            old_name='Endereço',
            new_name='ATIVIDADE',
        ),
        migrations.RenameField(
            model_name='empresas',
            old_name='Atividade_Economica_CNAE',
            new_name='Endereco',
        ),
        migrations.RenameField(
            model_name='empresas',
            old_name='Porte',
            new_name='PORTE',
        ),
        migrations.RenameField(
            model_name='empresas',
            old_name='Razao_Social',
            new_name='RazaoSocial',
        ),
    ]
